// usableIn: hvilke screen-kontekster der tillader USE
// color:    header-baggrundsfarve (hex)
// bg:       kortets stribe-baggrundsfarve (hex) — lys toning af color
// flavor:   undertekst på kortet (™-mærket)
// icon:     stort symbol vist i kortmidten (string)
export const CONSUMABLE_DEFS = [
    {
        id:          'extra_throw',
        name:        'CHOMPZ',
        flavor:      'Cherry Rush™',
        color:       '#cc2200',
        bg:          '#ffe0e0',
        icon:        '+1',
        description: '+1 throw this battle.',
        sellPrice:   3,
        usableIn:    ['battle'],
    },
    {
        id:          'double_next',
        name:        'DÜBBLE',
        flavor:      'Xtra Mint Blast™',
        color:       '#d4a800',
        bg:          '#fff3c0',
        icon:        '×2',
        description: 'Next throw scores ×2.',
        sellPrice:   4,
        usableIn:    ['battle'],
    },
    {
        id:          'refresh',
        name:        'FRESHIE',
        flavor:      'Cool Spearmint™',
        color:       '#00a0a0',
        bg:          '#d6f5f5',
        icon:        '↺',
        description: 'Shop: re-roll items free. Reward: re-roll picks.',
        sellPrice:   2,
        usableIn:    ['shop', 'reward'],
    },
    {
        id:          'enchant',
        name:        'MYSTIXX',
        flavor:      'Hexabubble™',
        color:       '#7722cc',
        bg:          '#ede0ff',
        icon:        '✦',
        description: 'Pick one cap from your collection. Apply a random enchant to it.',
        sellPrice:   5,
        usableIn:    ['battle', 'map', 'shop', 'reward'],
    },
    {
        id:          'white_card',
        name:        'BLANCO',
        flavor:      'Blank Slate™',
        color:       '#222222',
        bg:          '#e8e8e8',
        icon:        '🃏',
        description: 'Permanently transforms ALL your caps into random new ones.',
        sellPrice:   6,
        usableIn:    ['map', 'shop', 'reward'],
    },
    {
        id:          'clone',
        name:        'TWINSIES',
        flavor:      'Double Bubble™',
        color:       '#cc0077',
        bg:          '#ffe0f5',
        icon:        '◎',
        description: 'Pick 1 cap from Bag. Get a ghost copy for this round.',
        sellPrice:   5,
        usableIn:    ['battle'],
    },
    {
        id:          'transform',
        name:        'MUTTZ',
        flavor:      'Mystery Flavor™',
        color:       '#5a7a20',
        bg:          '#e8f0dc',
        icon:        '🎲',
        description: 'Pick 1 cap from your collection. Transform it into a random new one.',
        sellPrice:   4,
        usableIn:    ['map', 'shop', 'reward'],
    },
    {
        id:          'power_up',
        name:        'VOLTAGE',
        flavor:      'Electric Lemon™',
        color:       '#cc8800',
        bg:          '#ffffa0',
        icon:        '⚡',
        description: '+8 bonus value to ALL caps in the stack this round.',
        sellPrice:   4,
        usableIn:    ['battle'],
    },
    {
        id:          'double_relic',
        name:        'AMPLIFYZ',
        flavor:      'Twin Trigger™',
        color:       '#1144aa',
        bg:          '#d8e8ff',
        icon:        '◈',
        description: 'Next throw: all Relics trigger one extra time.',
        sellPrice:   5,
        usableIn:    ['battle'],
    },
];
